### ISSUE TITLE
[bug]: {"context": "core"} {"context": "core/relayer"} [TypeError: undefined is not a function]

### ISSUE THREAD

**Issue by shin101004** [WalletConnect/modal-react-native#91] opened 2023-10-13 09:31 UTC
### Description

{"context": "core"} {"context": "core/relayer"} [TypeError: undefined is not a function]

error happened.

i dont know why it happens.

### WalletConnect Modal SDK version

1.0.0-rc.11

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.18 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/jerry/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.10 => 0.71.10
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

connect wallet => disconnect => stay ... 

### Snack, code example, screenshot, or link to a repository

i think it occured when connect request continuously !

i update issue when it happens

---

I attach log.

![Error](https://github.com/WalletConnect/modal-react-native/assets/61345090/7e349d82-9853-4431-8a15-f7f26268037d)

--- 

attemptoToReconnect callled. Connecting...

after error occurred.
![스크린샷 2023-10-19 오후 10 29 56](https://github.com/WalletConnect/modal-react-native/assets/61345090/b980423f-00af-4838-89eb-c57d55d3a56f)

**Comment by glitch-txs** [comment] 2023-10-23 14:41
Hi could you share a very simple public repository or sandbox that reproduces this issue so we can run and test ourselves?

I'm closing this due to lack of info for now, feel free to reopen after adding a MRE. Thanks! 🙏

**Closed by glitch-txs** 2023-10-23 14:41 UTC
Labels: bug

**Comment by shin101004** [comment] 2023-10-26 07:24
i will provide repository until next week ! thx !

**Comment by SohaibMushtaq1243** [comment] 2023-10-31 05:59
i got the same problem on v2 please provide the solution if anyone find any

**Comment by Vyvtag** [comment] 2023-11-06 07:52
I'm getting this error too

**Comment by SohaibMushtaq1243** [comment] 2023-11-14 11:29
I am getting the same error anyone got the solution ???

**Comment by bao-cs** [comment] 2024-01-29 08:00
I am also getting the same error
