### ISSUE TITLE
[bug]: sending transaction infinite loading spinner on Rainbow

### ISSUE THREAD

**Issue by StevenBarnett1** [WalletConnect/modal-react-native#45] opened 2023-07-18 00:07 UTC
### Description

When trying to do a 2 step transaction (approval & next transaction) with signer.sendTransaction(), the second transaction shows an infinite loading spinner on rainbow. I've verified that the same transaction will work on trust wallet. This is probably a rainbow problem and I opened an issue with them, but i wanted to put it here as well just in case.

Approve works:
![IMG_4289](https://github.com/rainbow-me/rainbow/assets/73503506/30e8dd86-900a-43ff-9972-ce480fc2fb7f)
 APPROVAL TRANSACTION:  {"data": "0x095ea7b30000000000000000000000001231deb6f5749ef6ce6943a275a1d3e7486f4eae00000000000000000000000000000000000000000000000000000000000249f0", "to": "0x94b008aa00579c1307b0ef2c499ad98a8ce58e58"} 

Second transactions doesn't work.
![IMG_4290](https://github.com/WalletConnect/modal-react-native/assets/73503506/483d9af3-f106-4c97-816e-251470491dee)

BRIDGE TRANSACTION:  {"chainId": 10, "data": "0xd7556c1e000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000b40082a826c28249b77bcf86efcb0309d127b17a8fe8db7e989b2ac035cb894d4250000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c316070000000000000000000000000a6d42348465a40bdbea30eddf24f8076befcd7a00000000000000000000000000000000000000000000000000000000000242d7000000000000000000000000000000000000000000000000000000000000008900000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000873746172676174650000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008767962652d646578000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000001111111254eeb25477b68fb85ed929f73a9605820000000000000000000000001111111254eeb25477b68fb85ed929f73a96058200000000000000000000000094b008aa00579c1307b0ef2c499ad98a8ce58e580000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c3160700000000000000000000000000000000000000000000000000000000000249f000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000007c812aa3caf000000000000000000000000afea5601b0a894451955355e79ad3026515e500d00000000000000000000000094b008aa00579c1307b0ef2c499ad98a8ce58e580000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c31607000000000000000000000000afea5601b0a894451955355e79ad3026515e500d0000000000000000000000001231deb6f5749ef6ce6943a275a1d3e7486f4eae00000000000000000000000000000000000000000000000000000000000249f000000000000000000000000000000000000000000000000000000000000240cd0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000062800000000000000000000000000000000000000000000000000000000060a00a007e5c0d20000000000000000000000000000000000000000000005e600049600034600a0c9e75c4800000000000000002f030000000000000000000000000000000000000000000000000003180001c800a007e5c0d20000000000000000000000000000000000000000000001a400018a0000d05120c35dadb65012ec5796536bd9864ed8773abc74c494b008aa00579c1307b0ef2c499ad98a8ce58e58006402b9446c00000000000000000000000094b008aa00579c1307b0ef2c499ad98a8ce58e58000000000000000000000000afea5601b0a894451955355e79ad3026515e500d000000000000000000000000727defdf62a32fedb4d668206556f970f947d413000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004020727defdf62a32fedb4d668206556f970f947d413627dd56a0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000006000000000000000000000000094b008aa00579c1307b0ef2c499ad98a8ce58e58000000000000000000000000afea5601b0a894451955355e79ad3026515e500d00000000000000000000000000000000000000000000000000000000000000010020d6bdbf7842000000000000000000000000000000000000425126a132dab612db5cb9fc9ac426a0cc215a3423f9c994b008aa00579c1307b0ef2c499ad98a8ce58e580004f41766d80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014d49b830313cc200000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000afea5601b0a894451955355e79ad3026515e500d0000000000000000000000000000000000000000000000000000000064bc6836000000000000000000000000000000000000000000000000000000000000000100000000000000000000000094b008aa00579c1307b0ef2c499ad98a8ce58e58000000000000000000000000420000000000000000000000000000000000004200000000000000000000000000000000000000000000000000000000000000005126a132dab612db5cb9fc9ac426a0cc215a3423f9c942000000000000000000000000000000000000420004f41766d8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c613dfa652d57900000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000afea5601b0a894451955355e79ad3026515e500d0000000000000000000000000000000000000000000000000000000064bc6836000000000000000000000000000000000000000000000000000000000000000100000000000000000000000042000000000000000000000000000000000000420000000000000000000000008700daec35af8ff88c16bdf0418774cb3d7599b400000000000000000000000000000000000000000000000000000000000000005126a132dab612db5cb9fc9ac426a0cc215a3423f9c98700daec35af8ff88c16bdf0418774cb3d7599b40004f41766d8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000240cd00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000001111111254eeb25477b68fb85ed929f73a9605820000000000000000000000000000000000000000000000000000000064bc683600000000000000000000000000000000000000000000000000000000000000010000000000000000000000008700daec35af8ff88c16bdf0418774cb3d7599b40000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c3160700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002e9b3012000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000234f0000000000000000000000000000000000000000000000000000000000009d3ef0000000000000000000000000000000000000000000000000000c3b56591cf1c000000000000000000000000597f128e6e517b5a187aebc46a7a6b03502293f600000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000001474674dafd6f4495e7f63f7637e94b8b89b2f01db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000400082a826c28249b77bcf86efcb0309d127b17a8fe8db7e989b2ac035cb894d4250000000000000000000000000000000000000000000000000000000000000080000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f0000000000000000000000000a6d42348465a40bdbea30eddf24f8076befcd7a000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000001111111254eeb25477b68fb85ed929f73a9605820000000000000000000000001111111254eeb25477b68fb85ed929f73a9605820000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f00000000000000000000000000000000000000000000000000000000000234ef00000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000022812aa3caf000000000000000000000000cfd674f8731e801a4a15c1ae31770960e1afded10000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174000000000000000000000000c2132d05d31c914a87c6611c10748aeb04b58e8f000000000000000000000000b78906c8a461d6a39a57285c129843e1937c3278000000000000000000000000dd1305150d27aecc60c066630105db419977e36700000000000000000000000000000000000000000000000000000000000234ef0000000000000000000000000000000000000000000000000000000000022a5a0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000001600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008500000000000000000000000000000000000000000000000000000000006700206ae40711b8000f4240b78906c8a461d6a39a57285c129843e1937c32781111111254eeb25477b68fb85ed929f73a9605820000000000000000000000000000000000000000000000000000000000022a5a2791bca1f2de4661ed88a30c99a7a9449aa841740000000000000000000000000000000000000000000000000000002e9b3012000000000000000000000000000000000000000000000000", "from": "0x597f128e6e517b5a187aebc46a7a6b03502293f6", "gasLimit": "0x2470f2", "gasPrice": "0x58", "to": "0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE", "value": "0xc3b56591cf1c"}

### WalletConnect Modal SDK version

^1.0.0-rc.5

### Output of `npx react-native info`

N/A

### Steps to reproduce

Look at description

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by ignaciosantise** [comment] 2023-07-25 19:24
hey @StevenBarnett1 👋 as you said, if the same code works in Trust, then it's probably rainbow's issue. 

Can you create a public repo where the issue is reproducible? That might help them answer you. 

Anyway, im closing this as it appears not to be related to the SDK

**Closed by ignaciosantise** 2023-07-25 19:24 UTC
Labels: bug
