### ISSUE TITLE
[bug]: Unable to connect in React Native 0.68.1

### ISSUE THREAD

**Issue by DinhHoangNgoc** [WalletConnect/modal-react-native#30] opened 2023-07-11 05:29 UTC
### Description

My project is using React Native version 0.68.1. Based on the provided documentation, I have installed the V2 version into the project. However, when I try to initialize the functionality, I receive the error message: 'error initializing walletconnect sdk'. Other functions are not working as well.

### WalletConnect Modal SDK version

1.0.0-rc.5

### Output of `npx react-native info`

0.68.1

### Steps to reproduce

1 . Install the library.
2. Add the library to your project as instructed in the documentation.
3. Run the function and observe the error message displayed.

### Snack, code example, screenshot, or link to a repository

![e0c2509e4c759c2bc564](https://github.com/WalletConnect/modal-react-native/assets/99774920/04469167-55f9-4df2-bf0c-50795c8218c3)
![f55842045eef8eb1d7fe](https://github.com/WalletConnect/modal-react-native/assets/99774920/eb36657e-5343-4938-a17e-7ab599c81682)

**Comment by ignaciosantise** [comment] 2023-07-11 15:56
hey @DinhHoangNgoc 👋 Since React 17, there's no need to import `React` in every jsx file.
Can you try updating your babel and metro configs to this?

metro.config.js
```js
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: true,
      },
    }),
  },
};
```

babel.config.js
```js
module.exports = {
  presets: [
    ['module:metro-react-native-babel-preset', { useTransformReactJSXExperimental: true }],
  ],
  plugins: [
      [
          '@babel/plugin-transform-react-jsx',
          {
              runtime: 'automatic',
          },
      ],
  ],
};
```

**Comment by DinhHoangNgoc** [comment] 2023-07-12 03:56
Hi @ignaciosantise , I have made changes to the metro.config.js file as mentioned in my current project, but it still hasn't been resolved. I thought it might be due to additional libraries installed in my project causing additional errors, so I created a new project to try again, but this error still persists.

**Comment by DinhHoangNgoc** [comment] 2023-07-12 05:27
I have made changes as mentioned above, but I am still receiving the error: 'error initializing WalletConnect SDK'

**Comment by ignaciosantise** [comment] 2023-07-12 20:09
@DinhHoangNgoc do you still get the same error? `Can't find variable: React`? Are you using typescript?

If so, check if your `tsconfig.json` file has `"jsx": "react-jsx",`

**Comment by ignaciosantise** [comment] 2023-07-12 20:27
If it doesn't work either, can you provide an example repository with the issue? I'll be glad to help

**Comment by Ngoca1k15PT** [comment] 2023-07-13 06:51
@ignaciosantise The error 'Can't find variable: React' has been resolved, but the 'error initializing WalletConnect SDK' issue still remains unresolved. Do you have any suggestions on how to solve this problem?

**Comment by Ngoca1k15PT** [comment] 2023-07-13 07:21
Hi @ignaciosantise In my current project, there is still an error occurring, 'error initializing WalletConnect SDK.' I have created a new project using the latest version of React Native, and this error no longer appears. However, it doesn't display the connection confirmation popup when switching to MetaMask. You can view a demo of my project with React Native version 0.68.1 here: 
https://github.com/Ngoca1k15PT/DemoConnectWalletConnect

**Comment by Lauman** [comment] 2023-07-13 17:30
> hey @DinhHoangNgoc 👋 Since React 17, there's no need to import `React` in every jsx file. Can you try updating your babel and metro configs to this?
> 
> metro.config.js
> 
> ```js
> /**
>  * Metro configuration for React Native
>  * https://github.com/facebook/react-native
>  *
>  * @format
>  */
> 
> module.exports = {
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: true,
>         inlineRequires: true,
>       },
>     }),
>   },
> };
> ```
> 
> babel.config.js
> 
> ```js
> module.exports = {
>   presets: [
>     ['module:metro-react-native-babel-preset', { useTransformReactJSXExperimental: true }],
>   ],
>   plugins: [
>       [
>           '@babel/plugin-transform-react-jsx',
>           {
>               runtime: 'automatic',
>           },
>       ],
>   ],
> };
> ```
> 
> More info [here](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-a-jsx-transform)

Hello, I have a project with React Native 0.69.7 with typescript and with these config it does not work.
Is there another way to force that setting?
Thanks.

**Comment by ignaciosantise** [comment] 2023-07-13 17:56
> Hi @ignaciosantise In my current project, there is still an error occurring, 'error initializing WalletConnect SDK.' I have created a new project using the latest version of React Native, and this error no longer appears. However, it doesn't display the connection confirmation popup when switching to MetaMask. You can view a demo of my project with React Native version 0.68.1 here: https://github.com/Ngoca1k15PT/DemoConnectWalletConnect

@Ngoca1k15PT i cloned this demo and it does't throw the error `error initializing WalletConnect SDK`. But in Android it throws an error related with `BigInt` To solve that, you need to polyfill bigints

1. Run `yarn add big-integer`
2. Put this line at top of your root file
```js
if (typeof BigInt === 'undefined') global.BigInt = require('big-integer')

...

import { useWalletConnectModal } from '@walletconnect/modal-react-native';
```

----
About the Popup in metamask:
Can you check if your active network is the same that you have in your session proposal?
MetaMask doesn't show the popup unless you have the same active network...

For example, if your session chain is `chains: ['eip155:1'],`, you should have Ethereum Mainnet active in MM
 
<img width="477" alt="Screen Shot 2023-07-13 at 14 54 03" src="https://github.com/WalletConnect/modal-react-native/assets/25931366/6166e20b-2dc7-4c52-abb0-42adcf083ad3">

**Comment by DinhHoangNgoc** [comment] 2023-07-14 02:02
@ignaciosantise I have added the command line to the root file, and switched the metamask network to the network of the project that has been set up, but currently, the popup is still not appearing.

https://github.com/WalletConnect/modal-react-native/assets/99774920/f69d1125-b164-4f22-99a1-d6bb518da2c8

**Comment by kingingcole** [comment] 2023-07-14 23:31
I also get the error "Error Initializing WalletConnect SDK". When I manually edit the `initProvider` function in `useConfigure.ts` file to log the error in the catch block, it logs "[TypeError: Cannot convert null value to object]">

I am on RN v0.71.8 and @walletconnect/modal-react-native v1.0.0-rc.6. I was on RC.5 but thought to upgrade to 6. Issue exists in both. The SDK works super fine in iOS Simulators. I only get this error when I run it on my real iOS Device (iPhone 14 Pro Max running iOS 17 Public Beta).

**Comment by ignaciosantise** [comment] 2023-07-18 19:20
hey @kingingcole does the error started to appear on iOS 17? Can you check if it happens on iOS 16? The SDK has been tested in real devices and it works on iOS 16

**Comment by ignaciosantise** [comment] 2023-07-18 19:21
> @ignaciosantise I have added the command line to the root file, and switched the metamask network to the network of the project that has been set up, but currently, the popup is still not appearing.
> 
>  1282682729151743804.mp4

@DinhHoangNgoc please provide a public repo where the issue is reproducible.

**Comment by DinhHoangNgoc** [comment] 2023-07-24 01:43
@ignaciosantise I used this repository: 'https://github.com/Ngoca1k15PT/DemoConnectWalletConnect', and ran it on real devices:

Android: Google Pixel 7
iOS: iOS 16
However, it does not display the popup to confirm the connection.

**Comment by ignaciosantise** [comment] 2023-07-25 17:43
@DinhHoangNgoc the issue of the popup is related with MetaMask. MetaMask ignores some request's if they are not on the same chain.

Does the SDK work with another wallet like Trust?

**Comment by DinhHoangNgoc** [comment] 2023-07-26 02:00
hi @ignaciosantise , I haven't tried connecting through another wallet because my current project will only connect to the Metamask wallet. I'm also not sure if it's because Metamask rejects other wallets, but if I use this library on React Native version > 0.70, it still connects well (I have tried creating a project to test it).

**Comment by ignaciosantise** [comment] 2023-08-01 17:51
@harouf that's the solution. Did you cleaned the cache and restarted metro with `yarn start --reset-cache`?

If this doesn't work, can you create an example project where i can reproduce the issue?

**Comment by harouf** [comment] 2023-08-01 17:56
Yes, I cleaned everything but still facing the issue. It's a bit complicated to share the entire project but I will try to extract some portion of it in which I can still reproduce the issue.

**Comment by ignaciosantise** [comment] 2023-08-01 19:39
@harouf perfect, let me know when you have it. Also, which version of RN are you using? 
You can create an example app running `npx react-native@0.68.5 init DappExample --version 0.68.5` replacing the version with the one you are using, and add your basic code there

**Comment by harouf** [comment] 2023-08-02 15:54
@ignaciosantise I am using RN version `0.71.12` and I managed to get rid of the error after I removed the `yarn.lock` file and re-installed all dependencies afresh from scratch with new lock file generated. It's looking good now.

**Comment by ignaciosantise** [comment] 2023-08-10 17:00
> hey @DinhHoangNgoc 👋 Since React 17, there's no need to import `React` in every jsx file. Can you try updating your babel and metro configs to this?
> 
> babel.config.js
> 
> ```js
> module.exports = {
>   presets: [
>     ['module:metro-react-native-babel-preset', { useTransformReactJSXExperimental: true }],
>   ],
>   plugins: [
>       [
>           '@babel/plugin-transform-react-jsx',
>           {
>               runtime: 'automatic',
>           },
>       ],
>   ],
> };
> ```
> 
> Close your terminal and re-run `yarn start --reset-cache`
> 
> More info [here](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#whats-a-jsx-transform)

Im closing this as  "Can't find variable: React" issue is solved following the comment above.

**Closed by ignaciosantise** 2023-08-10 17:00 UTC
Labels: bug
