### ISSUE TITLE
Selecting View all Wallet list is failing with error: Cannnot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by jobinabraham** [WalletConnect/modal-react-native#38] opened 2023-07-13 08:40 UTC
### Description

When the list of wallet open, if I click on "View all" link at the end of the list, the app throws following error and becomes unresponsive. Attaching screen recording and screenshots as well. It seems some issue with flatlist being used by modal-react-native. I am using flatlist elesewhere in the project as well, only the modal-react-native implmentation is throwing error.

Error:
`Cannnot read property 'getItem' of undefined`

### WalletConnect Modal SDK version

1.0.0-rc.5

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 234.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: Not Found
    npm: 9.8.0 - ~/Developer/professional/wakanda/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open walletconnect modal by calling open method from useWalletConnectModal() hook.
2. Click on View All button at the end of all wallet list.

### Snack, code example, screenshot, or link to a repository

https://github.com/WalletConnect/modal-react-native/assets/9764162/6dcee6db-5337-47bb-9e76-8f83ac40d16b

![Screenshot_20230713-135955_OWN Games-Stage](https://github.com/WalletConnect/modal-react-native/assets/9764162/d431ded3-39f4-4986-aa21-54e3f1b04eec)

**Comment by ignaciosantise** [comment] 2023-07-13 15:57
Hey @jobinabraham i think your issue is related with this one https://github.com/facebook/react-native/issues/36828

Maybe this solution works for you: https://github.com/facebook/react-native/issues/36828#issuecomment-1589462227

**Comment by ignaciosantise** [comment] 2023-07-18 19:17
Closing this as i cannot reproduce it

**Closed by ignaciosantise** 2023-07-18 19:17 UTC
Labels: bug
