### ISSUE TITLE
[bug]: iOS Error initializing WalletConnect SDK shows on first install

### ISSUE THREAD

**Issue by m1heng** [WalletConnect/modal-react-native#8] opened 2023-06-26 09:22 UTC
### Description

During first install of iOS, user have to allow internet connection in order to have the app to call any API.
But in modal component -> useConfigure -> initProvider https://github.com/WalletConnect/modal-react-native/blob/435c95700f65f5588fb52ba0443aa606167094d3/src/hooks/useConfigure.ts#L87-L117
The initial call of `createUniversalProvider` would lead to an error since there are internet calls inside of it, which will leads to the alert of `Error initializing WalletConnect SDK`.

Also a side problem is that I happen to notice that `initProvider` would be called several times during the app start up.

### WalletConnect Modal SDK version

1.0.0-rc.2

### Output of `npx react-native info`

```
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 127.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.5 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

fresh iOS install launch

### Snack, code example, screenshot, or link to a repository

No capable

**Comment by m1heng** [comment] 2023-06-26 09:49
For the side question `Also a side problem is that I happen to notice that initProvider would be called several times during the app start up.` I just found out why.
When rendering WalletConnectModal, I wrote inline object porp for providerMetadata, which will finally leads to `Initialize provider Effect` got called not once.

**Comment by ignaciosantise** [comment] 2023-06-26 20:16
hey @m1heng 👋 is there a way you can render the modal after the permission is granted?

something like

`hasInternet && <WalletConnectModal ... />

**Comment by m1heng** [comment] 2023-06-27 02:45
We have a fork version of this, and we end up adding check in the useEffect
```
import { useNetInfo } from '@react-native-community/netinfo';
.
.
.
        if (!ClientCtrl.provider() && projectId && providerMetadata && netInfo.isConnected) {
            initProvider();
        }
    }, [projectId, providerMetadata, relayUrl, onDisplayUri, onSessionDelete, netInfo.isConnected]);
```

**Comment by m1heng** [comment] 2023-06-27 06:03
TBH, since this should be a globally used component, I think maybe it is better for component it self to well handle netinfo

**Comment by Z-Hayk** [comment] 2023-06-29 11:12
https://github.com/WalletConnect/modal-react-native/issues/15

**Comment by Z-Hayk** [comment] 2023-06-29 13:45
Hello.
Thus it works.

```
import { useNetInfo } from '@react-native-community/netinfo';

const netInfo = useNetInfo();

{netInfo.isConnected ? (
  <WalletConnectModal
    projectId={walletConnect.PROJECT_ID}
    providerMetadata={walletConnect.PROVIDER_METADATA}
    sessionParams={walletConnect.SESSION_PARAMS}
  />
) : null}
```

But I agree with @m1heng

**Comment by ignaciosantise** [comment] 2023-06-29 14:38
@m1heng @Z-Hayk thanks for the suggestion, i'll discuss it with the team. The idea is to keep this lib as small and simple as possible, so each peer dependency needs to be evaluated. For now, my suggestion is to render the Modal when connection is available.

Another possibility that may work is to add a boolean in the modal to run the initialization

something like this
```
<WalletConnectModal
    projectId={walletConnect.PROJECT_ID}
    ...
    initialize={netInfo.isConnected}
  />
```

**Comment by Z-Hayk** [comment] 2023-06-29 15:44
@ignaciosantise Thanks for the reply, but is there such an attribute?
I didn't find it in the props.

```
export type Props = Omit<ConfigCtrlState, 'recentWalletDeepLink'> &
  ThemeCtrlState & {
    providerMetadata: IProviderMetadata;
    sessionParams?: ISessionParams;
    relayUrl?: string;
    onCopyClipboard?: (value: string) => void;
  };
```

<img width="999" alt="Screenshot 2023-06-29 at 19 39 09" src="https://github.com/WalletConnect/modal-react-native/assets/122481542/93dbab33-3b83-4090-8677-ce2ce0a55c43">

**Comment by ignaciosantise** [comment] 2023-06-29 16:16
@Z-Hayk no, it's not available yet. I was thinking out-loud other possibilities without adding `netinfo`. Sorry for bringing confusion.

**Comment by venables** [comment] 2023-06-29 18:38
FWIW, we recently started to hit this error and it wasn't because of a network connection issue.  

We somehow got the app into a state where `AccountCtrl.getAccount` was throwing in `signer.getAddress()` (saying unknown operation).  We've been unable to get the app back into this state, unfortunately.

Uninstalling and reinstalling the app (to reset all state/storage) seemed to fix the issue.

**Comment by ignaciosantise** [comment] 2023-06-30 18:41
@venables thanks for pointing this out! If you find it again, please provide us the steps to reproduce it 🙏  Either way, that logic in AccountCtrl will change in the next release 💪

**Comment by ignaciosantise** [comment] 2023-07-04 20:34
hey guys, im closing this one as you can solve the issue by rendering the modal after the connection is established.

`hasInternet && <WalletConnectModal ... />`

If this brings problems in the future, we'll think another solution.

**Closed by ignaciosantise** 2023-07-04 20:34 UTC
Labels: bug

**Comment by dingcxx** [comment] 2023-07-06 08:46
I had the same problem

When I connected a wallet and then reload app will receive error 

> WalletConnect SDK error:  [Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)]

from blow code

```
  /**
   * Initialize provider
   */
  useEffect(() => {
    async function initProvider() {
      try {
        const provider = await createUniversalProvider({
          projectId,
          relayUrl,
          metadata: providerMetadata
        });
        if (provider) {
          ClientCtrl.setProvider(provider);
          provider.on('display_uri', onDisplayUri);
          provider.client.core.relayer.subscriber.on(SUBSCRIBER_EVENTS.deleted, onSessionDelete);

          // Check if there is an active session
          if (provider.session) {
            ClientCtrl.setSessionTopic(provider.session.topic);
            await AccountCtrl.getAccount();
          }
          ClientCtrl.setInitialized(true);
        }
      } catch (error) {
        console.log('WalletConnect SDK error:',error); // I added， and error here
        Alert.alert('Error', 'Error initializing WalletConnect SDK'); 
      }
```
could  the alert be removed?

and another problem is about `Network Error`

below is complete log

```
 INFO  {"context": "core"} Core Initialization Success
 INFO  {"context": "client"} SignClient Initialization Success
 LOG  WalletConnect SDK error: [Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)]
 WARN  Possible Unhandled Promise Rejection (id: 0):
"Network Error"
```

**Comment by dingcxx** [comment] 2023-07-06 09:06
I did not config sessionParams, and when I connect a wallet , the network is goerli and then I call `setDefaultchain` to  bnbt (chainId : 97), and read Contract method, I will receive Error:

>  [Error: underlying network changed (event="changed", network={"name":"goerli","chainId":5,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"name":"bnbt","chainId":97,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.7.2)]

So how request another network?

**Comment by ignaciosantise** [comment] 2023-07-07 18:31
@dingcxx can you check if the network error still happens in `v1.0.0-rc.5`?

**Comment by jupiterrosen** [comment] 2023-07-14 10:57
have the same problem and connot solve through adding netinfo.isconnected

**Comment by jupiterrosen** [comment] 2023-07-14 11:19
The detailed error under it is:
```
TypeError: Cannot convert null value to object
    at getPrototypeOf (native)
    at H (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:337824:33)
    at Sa (http://172.16.187.106:8081/node_modules\@walletconnect\universal-provider\dist\index.cjs.bundle//&platform=ios&hot=false&lazy=true&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:3926:26)
    at Bg (http://172.16.187.106:8081/node_modules\@walletconnect\universal-provider\dist\index.cjs.bundle//&platform=ios&hot=false&lazy=true&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:3919:15)
    at anonymous (http://172.16.187.106:8081/node_modules\@walletconnect\universal-provider\dist\index.cjs.bundle//&platform=ios&hot=false&lazy=true&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:4860:19)
    at forEach (native)
    at createProviders (http://172.16.187.106:8081/node_modules\@walletconnect\universal-provider\dist\index.cjs.bundle//&platform=ios&hot=false&lazy=true&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:4856:125)
    at ?anon_0_ (http://172.16.187.106:8081/node_modules\@walletconnect\universal-provider\dist\index.cjs.bundle//&platform=ios&hot=false&lazy=true&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:4810:102)
    at next (native)
    at asyncGeneratorStep (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6079:26)
    at _next (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:6098:29)
    at tryCallOne (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/private/var/folders/yw/6bx918xn4671rggfcdxz7fph0000gn/T/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39706:26)
    at _callTimer (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39585:17)
    at _callReactNativeMicrotasksPass (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39630:17)
    at callReactNativeMicrotasks (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:39836:44)
    at __callReactNativeMicrotasks (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3683:46)
    at anonymous (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3457:45)
    at __guard (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3656:15)
    at flushedQueue (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3456:21)
    at invokeCallbackAndReturnFlushedQueue (http://172.16.187.106:8081/index.bundle//&platform=ios&dev=true&hot=false&lazy=true:3450:33)
```

**Comment by CallbackDan** [comment] 2023-07-20 12:48
@ignaciosantise sorry- can't provide a public repo to help with the above. Is there a way we can supress the "Error initializing WalletConnect SDK" alert that pops up and let the developer handle the error ourselves?

**Comment by ignaciosantise** [comment] 2023-07-20 17:43
@CallbackDan  alerts will be removed in the next release. About the error you are having, about the public repo, i mean if you can create a basic example app that has the error

Running `npx react-native@latest init ExampleWithError` and adding the code that reproduces the issue you are having
