### ISSUE TITLE
[bug]: Error initializing WalletConnect SDK [TypeError: undefined is not an object (evaluating 'source.length')]

### ISSUE THREAD

**Issue by Francis11h** [WalletConnect/modal-react-native#89] opened 2023-10-08 08:51 UTC
### Description

after following this guide: https://docs.walletconnect.com/advanced/walletconnectmodal/usage
try to integrate WalletConnectModal into my project, every time show this error 
<img width="1072" alt="image" src="https://github.com/WalletConnect/modal-react-native/assets/42663441/4f0b5cc9-f4b3-480c-a1c2-1431481b65f2">

### WalletConnect Modal SDK version

1.0.0-rc.11

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 527.23 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.nvm/versions/node/v18.17.1/bin/node
  Yarn:
    version: 1.22.17
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.1/bin/npm
  Watchman:
    version: 2023.08.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

totally follow this guide : https://docs.walletconnect.com/advanced/walletconnectmodal/usage

### Snack, code example, screenshot, or link to a repository

import React, { useEffect, useMemo, useState } from 'react'
import { SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { useWalletConnectModal, WalletConnectModal } from '@walletconnect/modal-react-native'
import Clipboard from '@react-native-clipboard/clipboard'
import { numberToHex, sanitizeHex } from '@walletconnect/encoding'
import { ethers } from 'ethers'
import { Web3Provider } from '@ethersproject/providers'
import ContractUtils from './utils/ContractUtils'
import ConfigUtils from './utils/ConfigUtils'
import { RequestModal } from './components/RequestModal'

const WalletConnectModalPage: React.FC = () => {
  const { isConnected, provider, open, address, isOpen } = useWalletConnectModal()
  const [client, setClient] = useState<Web3Provider>()
  const [modalVisible, setModalVisible] = useState(false)
  const [rpcResponse, setRpcResponse] = useState<any>()
  const [loading, setLoading] = useState(false)

  // Init ethers client when the wallet is connected
  useEffect(() => {
    if (isConnected && provider) {
      const _client = new ethers.providers.Web3Provider(provider)
      console.log('init ethers when the wallet is connected, _client ...', _client)
      setClient(_client)
    }
  }, [isConnected, provider])

  const onConnect = async () => {
    if (isConnected) {
      return provider?.disconnect()
    }
    return await open()
  }

  const onCopy = (value: string) => {
    Clipboard.setString(value)
  }

  const onResponse = (response: any) => {
    setRpcResponse(response)
    setLoading(false)
  }

  const onModalClose = () => {
    setModalVisible(false)
    setLoading(false)
    setRpcResponse(undefined)
  }

  const onAction = (callback: any) => async () => {
    try {
      setLoading(true)
      setModalVisible(true)
      const response = await callback()
      onResponse(response)
    } catch (error: any) {
      onResponse({
        error: error?.message || 'error'
      })
    }
  }

  const onSendTransaction = async () => {
    if (!client) {
      return
    }

    const signer = client.getSigner()

    const { chainId } = await client.getNetwork()

    const amount = sanitizeHex(numberToHex(0.0001))
    const transaction = {
      to: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045', // vitalik.eth
      value: amount,
      chainId
    }

    // Send the transaction using the signer
    const txResponse = await signer.sendTransaction(transaction)
    const transactionHash = txResponse.hash
    console.log('transactionHash is ' + transactionHash)

    // Wait for the transaction to be mined (optional)
    const receipt = await txResponse.wait()
    console.log('Transaction was mined in block:', receipt.blockNumber)

    return {
      method: 'send transaction',
      blockNumber: receipt.blockNumber,
      result: transactionHash
    }
  }

  const onSignMessage = async () => {
    if (!client) {
      return
    }

    const [address] = await client.listAccounts()
    const signer = client.getSigner(address)

    const signature = await signer?.signMessage('Hello World!')
    return {
      method: 'sign message',
      signature: signature
    }
  }

  const onReadContract = async () => {
    const contract = new ethers.Contract(ContractUtils.contractAddress, ContractUtils.goerliABI, client)

    // Read contract information
    const totalSupply = await contract.totalSupply()

    return {
      method: 'read contract',
      data: totalSupply
    }
  }

  const onWriteContract = async () => {
    if (!client) {
      return
    }

    const [address] = await client.listAccounts()
    const signer = client.getSigner(address)

    const contract = new ethers.Contract(ContractUtils.contractAddress, ContractUtils.goerliABI, signer)

    const receipt = await contract.mint()
    const hash = receipt.hash
    console.log('receipt', receipt)
    return {
      method: 'write contract',
      response: hash
    }
  }

  return (
    <SafeAreaView>
      <View style={styles.container}>
        <TouchableOpacity style={styles.button} onPress={onConnect}>
          <Text style={styles.buttonText}>{isConnected ? 'Disconnect' : 'Connect'}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.button, !isConnected && styles.buttonDisabled]}
          disabled={!isConnected}
          onPress={onAction(onSendTransaction)}
        >
          <Text style={styles.buttonText}>Send Transaction</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.button, !isConnected && styles.buttonDisabled]}
          disabled={!isConnected}
          onPress={onAction(onSignMessage)}
        >
          <Text style={styles.buttonText}>Sign Message</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.button, !isConnected && styles.buttonDisabled]}
          disabled={!isConnected}
          onPress={onAction(onReadContract)}
        >
          <Text style={styles.buttonText}>Read Contract</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.button, !isConnected && styles.buttonDisabled]}
          disabled={!isConnected}
          onPress={onAction(onWriteContract)}
        >
          <Text style={styles.buttonText}>Write Contract</Text>
        </TouchableOpacity>
      </View>
      <WalletConnectModal
        projectId={'xxxxxx'}
        // projectId={ConfigUtils.PROJECT_ID}
        providerMetadata={ConfigUtils.providerMetadata}
        // sessionParams={ConfigUtils.sessionParams}
        onCopyClipboard={onCopy}
        // relayUrl="wss://relay.walletconnect.com"
      />
      <RequestModal isVisible={modalVisible} onClose={onModalClose} isLoading={loading} rpcResponse={rpcResponse} />
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center'
  },
  button: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#3396FF',
    borderRadius: 20,
    width: 200,
    height: 50,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    marginTop: 4
  },
  buttonDisabled: {
    backgroundColor: '#999'
  },
  buttonText: {
    color: 'white',
    fontWeight: '700'
  }
})

export default WalletConnectModalPage

**Comment by Francis11h** [comment] 2023-10-31 09:23
@ignaciosantise

**Comment by ignaciosantise** [comment] 2023-10-31 14:11
Hey @Francis11h! can you provide a repository with the reproducible issue?

you can run `npx react-native@latest init ModalExample` and add the code there

**Comment by ignaciosantise** [comment] 2023-11-08 19:26
Closing this as i cannot reproduce it. If it's still happing, please provide a public repository with the reproducible issue

**Closed by ignaciosantise** 2023-11-08 19:26 UTC
Labels: bug
